-- 1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND REGION TABLE

select COUNTRY_NAME,REGION_NAME
from COUNTRIES c inner join REGIONS r on c.REGION_ID = r.REGION_ID;

-- 2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
select FIRST_NAME,JOB_TITLE
from EMPLOYEES e inner join JOBS j on e.JOB_ID = j.JOB_ID;

select FIRST_NAME,JOB_TITLE
from EMPLOYEES  inner join JOBS  on EMPLOYEES.JOB_ID = JOBS.JOB_ID


-- 3. FIND OUT DEPARTMENT_NAME AND CITY

select DEPARTMENT_NAME,city
from DEPARTMENTS d inner join LOCATIONS l on d.LOCATION_ID=l.LOCATION_ID;

-- 4. FIND OUT ALL CITIES  AND COUNTRY NAMES

select CITY,COUNTRY_NAME,c.COUNTRY_ID
from COUNTRIES c inner join LOCATIONS L on c.COUNTRY_ID = l.COUNTRY_ID;


-- 5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME  FOR      DEPARTMENT ID 80 OR 40

select FIRST_NAME,LAST_NAME,DEPARTMENT_NAME,d.DEPARTMENT_ID
from DEPARTMENTS d inner join EMPLOYEES E on d.DEPARTMENT_ID = E.DEPARTMENT_ID
where d.DEPARTMENT_ID  IN(40,80);
;

-- 6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
select city,COUNTRY_NAME,REGION_NAME
from LOCATIONS l
         inner join COUNTRIES C on C.COUNTRY_ID = l.COUNTRY_ID
         inner join REGIONS r on C.REGION_ID = r.REGION_ID;

--  7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
select FIRST_NAME,JOB_TITLE,DEPARTMENT_NAME,CITY
from JOBS j inner join EMPLOYEES E on j.JOB_ID = E.JOB_ID
            inner join DEPARTMENTS D on D.DEPARTMENT_ID = E.DEPARTMENT_ID
            inner join LOCATIONS L on L.LOCATION_ID = D.LOCATION_ID;

-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY , COUNTRY_NAME , REGION_NAME





--9. FIND OUT  EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL DEPARTMENTS
--  INCLUDING  WHERE DO NOT HAVE ANY EMPLOYEE.
select * from DEPARTMENTS;
select * from EMPLOYEES;

select FIRST_NAME,LAST_NAME,d.DEPARTMENT_ID
from DEPARTMENTS d left outer join EMPLOYEES e on d.DEPARTMENT_ID = e.DEPARTMENT_ID;

select FIRST_NAME,LAST_NAME,d.DEPARTMENT_ID
from EMPLOYEES e right outer join DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID;


--10. FIND OUT ALL DEPARTMENT_NAME  , LOCATION_ID , AND COUNTRY_ID
-- INCLUDING THOSE LOCATIONS  WITH NO DEPARTMENT

select d.department_name , l.location_id ,  l.country_id
from departments d
         right outer join locations l on l.location_id = d.location_id
order by 1 ; --- we are ordering by first column so all nulls show in one place ;

--11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME
-- INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT
select d.department_name , l.location_id , c.country_name
from departments d
-- RETURN ALL MATCHING LOCATIONS FOR DEPARTMENTS + ANY LOCATION THAT DOES NOT MATCH DEPARTMENT LOCATION
         right outer join locations l on l.location_id = d.location_id
-- RETURN ALL MATCHING COUNTRIES FOR LOCATIONS + ANY COUNTRY THAT DOES NOT MATCH ANY LOCATION
         right outer join   countries c on l.country_id = c.country_id ;

--12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT NAME
-- INCLUDING THOSE DOES NOT HAVE DEPARTMENT
-- INCLUDING THOSE DEPARTMENTS  DOES NOT HAVE ANY MATCHING EMPLOYEES

select FIRST_NAME,d.DEPARTMENT_ID,DEPARTMENT_NAME
from EMPLOYEES e full outer join DEPARTMENTS D on D.DEPARTMENT_ID = e.DEPARTMENT_ID;